### ISSUE TITLE
Seurat

### ISSUE THREAD

**Issue by Dena2021** [JSB-UCLA/scDED#1]
Hello scDEED developers, 
Thanks for making this tool available. 
Can you please provide a tutorial or script how to try it with a Seurat object. 
Thanks

**Comment by clee700** [comment]
Hello, 
Thank you for your interest in our tool. Actually, the code is compatible with Seurat objects. You should be able to just use the Seurat object in place of the 'input_counts' object. If you input a counts matrix, it will be turned into a Seurat object.

**Comment by clee700** [comment]
In the new version of the package, you can no longer supply a matrix; it must be a Seurat object.
