### ISSUE TITLE
Running scDEED on SCT data

### ISSUE THREAD

**Issue by jcorn427** [JSB-UCLA/scDED#11]
Hello! Your tool seems very interesting and I'd really like to use it on my dataset, however, I'm getting the following error when running it on my SCTransformed seurat object:

`Error in scDEED(lung_seurat, K = 30, reduction.method = "UMAP") : 
  object 'dub_para' not found`

I tried running scDEED on the demo data and it worked fine so that's not the issue. The only thing that is different is that I set default_assay to "SCT". Here's the command I ran:

`result <- scDEED(lung_seurat, K = 30, reduction.method = "UMAP", default_assay = 'SCT', slot = 'scale.data')`

Any help would be much appreciated. Thanks!

Here's my session info:
`─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.0 (2024-04-24)
 os       Ubuntu 22.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2024-12-11
 rstudio  2024.04.1+748 Chocolate Cosmos (server)
 pandoc   3.1.13 @ /usr/bin/pandoc

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package              * version  date (UTC) lib source
   abind                  1.4-8    2024-09-12 [1] RSPM (R 4.4.0)
   beachmat               2.20.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   Biobase                2.64.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   BiocGenerics           0.50.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   BiocParallel           1.38.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   BiocSingular           1.20.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   bitops                 1.0-9    2024-10-03 [1] RSPM (R 4.4.0)
   cachem                 1.1.0    2024-05-16 [2] RSPM (R 4.4.0)
   callr                  3.7.6    2024-03-25 [2] RSPM (R 4.4.0)
   caTools                1.18.3   2024-09-04 [1] RSPM (R 4.4.0)
   cli                    3.6.3    2024-06-21 [1] RSPM (R 4.4.0)
   cluster                2.1.6    2023-12-01 [3] CRAN (R 4.4.0)
   codetools              0.2-20   2024-03-31 [3] CRAN (R 4.4.0)
   colorspace             2.1-1    2024-07-26 [1] RSPM (R 4.4.0)
   cowplot                1.1.3    2024-01-22 [1] RSPM (R 4.4.0)
   crayon                 1.5.3    2024-06-20 [1] RSPM (R 4.4.0)
   curl                   6.0.1    2024-11-14 [1] RSPM (R 4.4.0)
 V data.table           * 1.16.2   2024-12-06 [1] RSPM (R 4.4.0) (on disk 1.16.4)
   DelayedArray           0.30.1   2024-05-07 [2] Bioconductor 3.19 (R 4.4.0)
   DelayedMatrixStats     1.26.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   deldir                 2.0-4    2024-02-28 [1] RSPM (R 4.4.0)
   desc                   1.4.3    2023-12-10 [2] RSPM (R 4.4.0)
   devtools             * 2.4.5    2022-10-11 [2] RSPM (R 4.4.0)
   digest                 0.6.37   2024-08-19 [1] RSPM (R 4.4.0)
   distances            * 0.1.11   2024-07-31 [1] RSPM (R 4.4.0)
   doParallel           * 1.0.17   2022-02-07 [2] RSPM (R 4.4.0)
   dotCall64              1.2      2024-10-04 [1] RSPM (R 4.4.0)
   dplyr                * 1.1.4    2023-11-17 [2] RSPM (R 4.4.0)
   dqrng                  0.4.1    2024-05-28 [1] RSPM (R 4.4.0)
   ellipsis               0.3.2    2021-04-29 [2] RSPM (R 4.4.0)
   fansi                  1.0.6    2023-12-08 [2] RSPM (R 4.4.0)
   farver                 2.1.2    2024-05-13 [2] RSPM (R 4.4.0)
   fastDummies            1.7.4    2024-08-16 [1] RSPM (R 4.4.0)
   fastmap                1.2.0    2024-05-15 [2] RSPM (R 4.4.0)
   fitdistrplus           1.2-1    2024-07-12 [1] RSPM (R 4.4.0)
   foreach              * 1.5.2    2022-02-02 [2] RSPM (R 4.4.0)
   fs                     1.6.5    2024-10-30 [1] RSPM (R 4.4.0)
   future                 1.34.0   2024-07-29 [1] RSPM (R 4.4.0)
   future.apply           1.11.3   2024-10-27 [1] RSPM (R 4.4.0)
   generics               0.1.3    2022-07-05 [2] RSPM (R 4.4.0)
   GenomeInfoDb           1.40.1   2024-05-24 [2] Bioconductor 3.19 (R 4.4.0)
   GenomeInfoDbData       1.2.12   2024-11-21 [1] Bioconductor
   GenomicRanges          1.56.0   2024-05-01 [2] Bioconductor 3.19 (R 4.4.0)
   ggplot2              * 3.5.1    2024-04-23 [2] RSPM (R 4.4.0)
   ggrepel                0.9.6    2024-09-07 [1] RSPM (R 4.4.0)
   ggridges               0.5.6    2024-01-23 [1] RSPM (R 4.4.0)
   glmGamPoi              1.16.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   globals                0.16.3   2024-03-08 [1] RSPM (R 4.4.0)
   glue                   1.8.0    2024-09-30 [1] RSPM (R 4.4.0)
   goftest                1.2-3    2021-10-07 [1] RSPM (R 4.4.0)
   gplots               * 3.2.0    2024-10-05 [1] RSPM (R 4.4.0)
   gridExtra            * 2.3      2017-09-09 [1] RSPM (R 4.4.0)
   gtable                 0.3.6    2024-10-25 [1] RSPM (R 4.4.0)
   gtools                 3.9.5    2023-11-20 [1] RSPM (R 4.4.0)
   htmltools              0.5.8.1  2024-04-04 [2] RSPM (R 4.4.0)
   htmlwidgets            1.6.4    2023-12-06 [2] RSPM (R 4.4.0)
   httpuv                 1.6.15   2024-03-26 [2] RSPM (R 4.4.0)
   httr                   1.4.7    2023-08-15 [2] RSPM (R 4.4.0)
   ica                    1.0-3    2022-07-08 [1] RSPM (R 4.4.0)
 V igraph                 2.1.1    2024-12-07 [1] RSPM (R 4.4.0) (on disk 2.1.2)
   IRanges                2.38.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   irlba                  2.3.5.1  2022-10-03 [1] RSPM (R 4.4.0)
   iterators            * 1.0.14   2022-02-05 [2] RSPM (R 4.4.0)
   jsonlite               1.8.9    2024-09-20 [1] RSPM (R 4.4.0)
   KernSmooth             2.23-22  2023-07-10 [3] CRAN (R 4.4.0)
   labeling               0.4.3    2023-08-29 [2] RSPM (R 4.4.0)
   later                  1.4.1    2024-11-27 [1] RSPM (R 4.4.0)
   lattice                0.22-6   2024-03-20 [3] CRAN (R 4.4.0)
   lazyeval               0.2.2    2019-03-15 [1] RSPM (R 4.4.0)
   leiden                 0.4.3.1  2023-11-17 [1] RSPM (R 4.4.0)
   lifecycle              1.0.4    2023-11-07 [2] RSPM (R 4.4.0)
   listenv                0.9.1    2024-01-29 [1] RSPM (R 4.4.0)
   lmtest                 0.9-40   2022-03-21 [1] RSPM (R 4.4.0)
   magrittr             * 2.0.3    2022-03-30 [2] RSPM (R 4.4.0)
   MASS                   7.3-61   2024-06-13 [1] RSPM (R 4.4.0)
   Matrix                 1.7-1    2024-10-18 [1] RSPM (R 4.4.0)
   MatrixGenerics         1.16.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   matrixStats            1.4.1    2024-09-08 [1] RSPM (R 4.4.0)
   memoise                2.0.1    2021-11-26 [2] RSPM (R 4.4.0)
   mime                   0.12     2021-09-28 [2] RSPM (R 4.4.0)
   miniUI                 0.1.1.1  2018-05-18 [2] RSPM (R 4.4.0)
   munsell                0.5.1    2024-04-01 [2] RSPM (R 4.4.0)
   nlme                   3.1-166  2024-08-14 [1] RSPM (R 4.4.0)
   parallelly             1.40.1   2024-12-04 [1] RSPM (R 4.4.0)
   patchwork            * 1.3.0    2024-09-16 [1] RSPM (R 4.4.0)
   pbapply                1.7-2    2023-06-27 [1] RSPM (R 4.4.0)
   PCAtools               2.16.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   pillar                 1.9.0    2023-03-22 [2] RSPM (R 4.4.0)
   pkgbuild               1.4.5    2024-10-28 [1] RSPM (R 4.4.0)
   pkgconfig              2.0.3    2019-09-22 [2] RSPM (R 4.4.0)
   pkgload                1.3.4    2024-01-16 [2] RSPM (R 4.4.0)
   plotly                 4.10.4   2024-01-13 [1] RSPM (R 4.4.0)
   plyr                   1.8.9    2023-10-02 [1] RSPM (R 4.4.0)
   png                    0.1-8    2022-11-29 [1] RSPM (R 4.4.0)
   polyclip               1.10-7   2024-07-23 [1] RSPM (R 4.4.0)
   pracma               * 2.4.4    2023-11-10 [1] RSPM (R 4.4.0)
   processx               3.8.4    2024-03-16 [2] RSPM (R 4.4.0)
   profvis                0.3.8    2023-05-02 [2] RSPM (R 4.4.0)
   progressr              0.15.1   2024-11-22 [1] RSPM (R 4.4.0)
   promises               1.3.2    2024-11-28 [1] RSPM (R 4.4.0)
   ps                     1.8.1    2024-10-28 [1] RSPM (R 4.4.0)
   purrr                  1.0.2    2023-08-10 [2] RSPM (R 4.4.0)
   R6                     2.5.1    2021-08-19 [2] RSPM (R 4.4.0)
   RANN                   2.6.2    2024-08-25 [1] RSPM (R 4.4.0)
   RColorBrewer           1.1-3    2022-04-03 [2] RSPM (R 4.4.0)
   Rcpp                   1.0.13-1 2024-11-02 [1] RSPM (R 4.4.0)
   RcppAnnoy              0.0.22   2024-01-23 [1] RSPM (R 4.4.0)
   RcppHNSW               0.6.0    2024-02-04 [1] RSPM (R 4.4.0)
   remotes                2.5.0    2024-03-17 [2] RSPM (R 4.4.0)
   resample             * 0.6      2022-06-13 [1] RSPM (R 4.4.0)
   reshape2               1.4.4    2020-04-09 [1] RSPM (R 4.4.0)
   reticulate             1.40.0   2024-11-15 [1] RSPM (R 4.4.0)
   rlang                  1.1.4    2024-06-04 [1] RSPM (R 4.4.0)
   ROCR                   1.0-11   2020-05-02 [1] RSPM (R 4.4.0)
   RSpectra               0.16-2   2024-07-18 [1] RSPM (R 4.4.0)
   rstudioapi             0.17.1   2024-10-22 [1] RSPM (R 4.4.0)
   rsvd                   1.0.5    2021-04-16 [2] RSPM (R 4.4.0)
   Rtsne                  0.17     2023-12-07 [1] RSPM (R 4.4.0)
   S4Arrays               1.4.1    2024-05-20 [2] Bioconductor 3.19 (R 4.4.0)
   S4Vectors              0.42.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   ScaledMatrix           1.12.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   scales                 1.3.0    2023-11-28 [2] RSPM (R 4.4.0)
   scattermore            1.2      2023-06-12 [1] RSPM (R 4.4.0)
   scDEED               * 0.1.0    2024-12-11 [1] Github (JSB-UCLA/scDEED@25282e8)
   sctransform            0.4.1    2023-10-19 [1] RSPM (R 4.4.0)
   sessioninfo            1.2.2    2021-12-06 [2] RSPM (R 4.4.0)
   Seurat               * 5.1.0    2024-05-10 [1] RSPM (R 4.4.0)
   SeuratObject         * 5.0.2    2024-05-08 [1] RSPM (R 4.4.0)
   shiny                  1.9.1    2024-08-01 [1] RSPM (R 4.4.0)
   sp                   * 2.1-4    2024-04-30 [1] RSPM (R 4.4.0)
   spam                   2.11-0   2024-10-03 [1] RSPM (R 4.4.0)
   SparseArray            1.4.8    2024-05-24 [2] Bioconductor 3.19 (R 4.4.0)
   sparseMatrixStats      1.16.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   spatstat.data          3.1-4    2024-11-15 [1] RSPM (R 4.4.0)
   spatstat.explore       3.3-3    2024-10-22 [1] RSPM (R 4.4.0)
   spatstat.geom          3.3-4    2024-11-18 [1] RSPM (R 4.4.0)
   spatstat.random        3.3-2    2024-09-18 [1] RSPM (R 4.4.0)
   spatstat.sparse        3.1-0    2024-06-21 [1] RSPM (R 4.4.0)
   spatstat.univar        3.1-1    2024-11-05 [1] RSPM (R 4.4.0)
   spatstat.utils         3.1-1    2024-11-03 [1] RSPM (R 4.4.0)
   stringi                1.8.4    2024-05-06 [2] RSPM (R 4.4.0)
   stringr              * 1.5.1    2023-11-14 [2] RSPM (R 4.4.0)
   SummarizedExperiment   1.34.0   2024-05-01 [2] Bioconductor 3.19 (R 4.4.0)
   survival               3.7-0    2024-06-05 [1] RSPM (R 4.4.0)
   tensor                 1.5      2012-05-05 [1] RSPM (R 4.4.0)
   tibble                 3.2.1    2023-03-20 [2] RSPM (R 4.4.0)
   tidyr                  1.3.1    2024-01-24 [2] RSPM (R 4.4.0)
   tidyselect             1.2.1    2024-03-11 [2] RSPM (R 4.4.0)
   UCSC.utils             1.0.0    2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   urlchecker             1.0.1    2021-11-30 [2] RSPM (R 4.4.0)
   usethis              * 2.2.3    2024-02-19 [2] RSPM (R 4.4.0)
   utf8                   1.2.4    2023-10-22 [2] RSPM (R 4.4.0)
   uwot                   0.2.2    2024-04-21 [1] RSPM (R 4.4.0)
   vctrs                  0.6.5    2023-12-01 [2] RSPM (R 4.4.0)
   VGAM                 * 1.1-12   2024-09-18 [1] RSPM (R 4.4.0)
   viridisLite            0.4.2    2023-05-02 [2] RSPM (R 4.4.0)
   withr                  3.0.2    2024-10-28 [1] RSPM (R 4.4.0)
   xtable                 1.8-4    2019-04-21 [2] RSPM (R 4.4.0)
   XVector                0.44.0   2024-04-30 [2] Bioconductor 3.19 (R 4.4.0)
   zlibbioc               1.50.0   2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   zoo                    1.8-12   2023-04-13 [1] RSPM (R 4.4.0)

 [1] /gscratch/kawaldorflab/jcorn427/R
 [2] /usr/local/lib/R/site-library
 [3] /usr/local/lib/R/library

 V ── Loaded and on-disk version mismatch.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

**Comment by jcorn427** [comment]
Actually, I just reran it on my own data after doing the standard Seurat pipeline and got the same error. This makes me think there's something going on with my seurat object that scDEED doesn't like.

**Comment by JSB-UCLA** [comment]
Thank you for your interest and question, John! We will look into this
issue and get back to you next week.

Best,
Jessica

**Comment by clee700** [comment]
Hi John! Thank you for being patient. 

The solution turns out to be a formatting issue- it should be `reduction.method = "umap"` (lowercase). R is case-sensitive; when you use UMAP (all caps), this is not recognized as one of the options. 

I confirmed this does work when I use a sample Seurat PBMC dataset with SCTransform. 

Hope that fixes the issue, please let us know if not. 

Best, 
Christy

**Comment by jcorn427** [comment]
Oh my goodness, it was that simple. Thank you! That seems to have solved my issue.

**Comment by clee700** [comment]
Glad to help! I've added a line to make the input `reduction.method` lowercase, so this won't affect future users.
