### ISSUE TITLE
Missing arguments in scDEED documentation

### ISSUE THREAD

**Issue by lgatto** [JSB-UCLA/scDED#6]
The `rerun` argument is missing in `?scDEED`.

**Comment by lgatto** [comment]
This also applies to the `permuted` argument.

**Comment by clee700** [comment]
Hi, 
Apologies, the manual page was incorrect. I overlooked the manual page while doing the update. It is updated now. Please re-install the package to the latest version. 

Best, 
Christy

**Comment by lgatto** [comment]
Thanks!
