### ISSUE TITLE
Missing man page for Permuted

### ISSUE THREAD

**Issue by lgatto** [JSB-UCLA/scDED#7]
`?scDEED::Permuted`

says that there's no documentation for ‘Permuted’.

**Comment by lgatto** [comment]
This is the case for all exported functions except `scDEED`.

**Comment by clee700** [comment]
Please re-download the package; this has been  updated and documentation for all functions has been added. Additionally, more information has been added to the scDEED documentation. Apologies for all the re-downloading!
