### ISSUE TITLE
scDEED on CCA integrated data

### ISSUE THREAD

**Issue by detectivelouis** [JSB-UCLA/scDED#8]
When running scDEED after integrating 3 Seurat objects into one using CCA, I get an error at the "`permuting data`" step. The error says `Error in X[i, row] : subscript out of bounds`. I don't get this error when the 3 Seurat objects are merged using the `merge()` function. I tried changing the default assay to RNA but the error persisted. Any tips to run scDEED on integrated data?
Thank you very much for your help.

**Comment by clee700** [comment]
Hello, 
Thanks for your interest in scDEED! 
I believe there are 2 potential sources of error. 
1. After integration, what is the default assay? I believe it will be changed to 'integrated'. Please specify this in Permuted(default_assay = 'integrated'). 
2. Did you run ScaleData on the integrated assay?

If you were using the scDEED function, please re-install the package (the default_assay argument was missing from scDEED, and has now been updated). 

Please let us know if that does not fix it. 

Best, 
Christy

**Comment by detectivelouis** [comment]
Thanks for getting back to me.
1) Yes, after integration the default assay is "integrated"
2) Yes, I am running `ScaleData()` after integration.

In short even after running the `Permuted()` function the error persists when running `scDEED()`.
Here is my code and the error I am getting. Please let me know if it should be changed. Thanks.

`
> DefaultAssay(data)
[1] "integrated"

> data <- ScaleData(data)
Centering and scaling data matrix
|=============================================================================================================================================| 100%

> data <- RunPCA(pfa, verbose = F)
Warning: Number of dimensions changing from 20 to 50

> data <- RunTSNE(data)

> data <- Permuted(data, default_assay = "integrated", K = K)
|=================================================================================================================                            |  80%PC_ 1 
Positive:  PRUNE2, GABRG3, TMEM108, AIM2, NNAT, NCAM2, AC087280.2, AKAP6, HGF, AC092691.1 
	   KIT, RGS2, COL23A1, ETS1, PADI2, AC004594.1, CDH18, TIMP3, B3GALNT2, AC092422.1 
	   EDA, MGAT4A, AC110296.1, AC073050.1, AL356108.1, AC004949.1, AL033504.1, FCGR2A, FLT1, APOD 
Negative:  STPG2, CFAP58, GABRB1, AC009041.2, HDX, IFI44L, LDLR, P3H2, PITPNC1, NUSAP1 
	   USP53, SPATA9, MUSK, PRDM6, AC024901.1, ADGRB3, FRMD4B, AC002072.1, GABBR2, AC008014.1 
	   AC004083.1, AL365295.1, FRY, AMPH, TEKT1, APBB1IP, AC104574.2, SLC1A2, RCSD1, TGFBR2 

> result <- scDEED(data, K = K, reduction.method = 'tsne', perplexity = 40, rerun = F)
[1] "Permuting data"
  |========================================================                                                                                     |  40%Error in X[i, row] : subscript out of bounds

>
`

**Comment by clee700** [comment]
You need to specify the default_assay in the scDEED function as well.

**Comment by detectivelouis** [comment]
That worked. Thanks a lot!!
Here is the code:
`result <- scDEED(data, K = K, reduction.method = 'tsne', perplexity = 40, rerun = F, default_assay = 'integrated')`

Also, this is running without the need to run the `Permute()` function before it. Am I right in doing that?

**Comment by clee700** [comment]
Yes, that's correct! The scDEED function includes Permute(), so you only need to feed in the original data.
